[tools]
atuin = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
"github:cmhughes/latexindent.pl" = { version = "latest", matching = "latexindent", bin = "latexindent" }
"github:latex-lsp/texlab" = "latest"
go = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
herdr = "latest"
hunk = "latest"
jq = "latest"
lazygit = "latest"
lua-language-server = "latest"
neovim = "latest"
node = "lts"
"npm:@fsouza/prettierd" = "latest"
"npm:pyright" = "latest"
pi = "latest"
ripgrep = "latest"
ruff = "latest"
shellcheck = "latest"
starship = "latest"
stylua = "latest"
tree-sitter = "latest"
uv = "latest"
zoxide = "latest"
